[project]
authors = ["Davoody, Amirhossein <amirhossein.davoodi@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "all-my-config-files"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
libc = {family = "glibc", version = "2.22"}
linux = "4.12.14"

[dependencies]
just = ">=1.34.0,<2"

[activation]
scripts = [
  "activation.sh",
]
